In [43]:
import numpy as np 

In [44]:
array1 = np.array([1,2,3,4,5,6])

In [45]:
array2 = np.empty((2,3))
array2

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [46]:
array1.ndim

1

In [47]:
array2.shape

(2, 3)

In [48]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,20]])

In [49]:
array3.shape

(2, 5)

In [50]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

How to reshape the array 

In [51]:
array3.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 20]])

In [52]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

In [53]:
array3.shape

(2, 5)

In [54]:
array3.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [20]])

# Indexing and slicing 

In [55]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [56]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [57]:
print(array3[1,2])

8


In [58]:
array4 = np.array((2,5),dtype=np.int64)
array4

array([2, 5])

In [59]:
row = array3[1,:]
row

array([ 6,  7,  8,  9, 10])

In [60]:
# Access 2nd colum
col = array3[:,1]
col

array([ 2,  7, 12,  2,  7, 12])

In [61]:
rows_slice = array3[0:2, :] # Selects the first two rows (indices 0 and 1)
print(rows_slice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [62]:
sub_array = array3[0:2, 0:2] # Selects the top-left 2x2 sub-array
print(sub_array)

[[1 2]
 [6 7]]


In [63]:
stepped_rows = array3[::2, :] # Selects every other row
print(stepped_rows)


[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [ 6  7  8  9 10]]


In [64]:
tes1 = np.arange(0,100,5)

In [65]:
tes1.reshape(2,10)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [66]:
np.linspace(0,100,10, dtype=np.int64)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [67]:
x = np.linspace(0,10,num=10,dtype=np.int64)
x = x.reshape(5,2)
y = np.linspace(11,100,num=10,dtype=np.int64)
y = y.reshape(5,2)
t = np.concatenate((x,y),axis=0)
t

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,  10],
       [ 11,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

# Arithmetic operation 

In [68]:
t1 = np.ones(shape=(2,5),dtype=np.int64)
t2 = np.ones(shape=(2,5),dtype=np.int64)

In [69]:
t3 = t1-t2
t3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# summation of values 

In [70]:
t4 = np.arange(start=1,stop=100,step=5)
t4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [71]:
print(t4.sum())

970


In [72]:
print(t4.min())

1


# Broadcasting

In [77]:
array_8 = np.linspace(0.0,1.0,num=15,dtype=np.float64)
array_8 = array_8 * 5
array_8

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [78]:
array_9 = array_8 > 3
array_9

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [81]:
array_8[array_8>1.5]

array([1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [82]:
array_8[(array_8>1.5) & (array_8<4.3)]

array([1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429])

In [83]:
np.save("temp_np",array_8)

In [84]:
test = np.load("temp_np.npy")
test

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])