In [61]:
import numpy as np 

In [62]:
array1 = np.array([1,2,3,4,5,6])

In [63]:
array2 = np.empty((2,3))
array2

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [64]:
array1.ndim

1

In [65]:
array2.shape

(2, 3)

In [66]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,20]])

In [67]:
array3.shape

(2, 5)

In [68]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

How to reshape the array 

In [69]:
array3.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 20]])

In [70]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

In [71]:
array3.shape

(2, 5)

In [72]:
array3.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [20]])

# Indexing and slicing 

In [73]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [74]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [75]:
print(array3[1,2])

8


In [76]:
array4 = np.array((2,5),dtype=np.int64)
array4

array([2, 5])

In [77]:
row = array3[1,:]
row

array([ 6,  7,  8,  9, 10])

In [78]:
# Access 2nd colum
col = array3[:,1]
col

array([ 2,  7, 12,  2,  7, 12])

In [79]:
rows_slice = array3[0:2, :] # Selects the first two rows (indices 0 and 1)
print(rows_slice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [80]:
sub_array = array3[0:2, 0:2] # Selects the top-left 2x2 sub-array
print(sub_array)

[[1 2]
 [6 7]]


In [81]:
stepped_rows = array3[::2, :] # Selects every other row
print(stepped_rows)


[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [ 6  7  8  9 10]]


In [82]:
tes1 = np.arange(0,100,5)

In [83]:
tes1.reshape(2,10)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [84]:
np.linspace(0,100,10, dtype=np.int64)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [85]:
x = np.linspace(0,10,num=10,dtype=np.int64)
x = x.reshape(5,2)
y = np.linspace(11,100,num=10,dtype=np.int64)
y = y.reshape(5,2)
t = np.concatenate((x,y),axis=0)
t

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,  10],
       [ 11,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

# Arithmetic operation 

In [86]:
t1 = np.ones(shape=(2,5),dtype=np.int64)
t2 = np.ones(shape=(2,5),dtype=np.int64)

In [87]:
t3 = t1-t2
t3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# summation of values 

In [88]:
t4 = np.arange(start=1,stop=100,step=5)
t4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [89]:
print(t4.sum())

970


In [90]:
print(t4.min())

1


# Broadcasting

In [91]:
array_8 = np.arange(start=0,stop=100,step = 3,dtype=np.int64)
array_8

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [92]:
array_8.size

34

In [93]:
array_9 = array_8 > 3
array_9

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [94]:
array_8[array_8>1.5]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [95]:
array_8[(array_8>1.5) & (array_8<50)]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [96]:
#np.save("temp_np",array_8)

In [97]:
#test = np.load("temp_np.npy")
#test

In [98]:
even = array_8[(array_8%2==0)]
even

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [99]:
34/2

17.0

In [100]:
arr_2d = array_8.reshape(17,2)
arr_2d

array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21],
       [24, 27],
       [30, 33],
       [36, 39],
       [42, 45],
       [48, 51],
       [54, 57],
       [60, 63],
       [66, 69],
       [72, 75],
       [78, 81],
       [84, 87],
       [90, 93],
       [96, 99]])

In [ ]:
for row in arr_2d:
    print("new row ")
    print(row)

new row 
[0 3]
new row 
[6 9]
new row 
[12 15]
new row 
[18 21]
new row 
[24 27]
new row 
[30 33]
new row 
[36 39]
new row 
[42 45]
new row 
[48 51]
new row 
[54 57]
new row 
[60 63]
new row 
[66 69]
new row 
[72 75]
new row 
[78 81]
new row 
[84 87]
new row 
[90 93]
new row 
[96 99]


In [ ]:
# The -1 specifies that the size should be infered base on the size of the array
arr = np.random.randint(1, 101, 100).reshape(10, -1)
arr.shape

(10, 10)

In [104]:
matrix = np.eye(4)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [105]:
result = np.diagonal(matrix)
print(result)

[1. 1. 1. 1.]


In [106]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

# Concatenate horizontally using hstack
result_hstack = np.hstack((arr1, arr2))
print("Result using hstack:")
print(result_hstack)

Result using hstack:
[[1 2 5 6]
 [3 4 7 8]]


In [107]:
import numpy as np
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
result = np.trace(arr)
print(result)

15


In [110]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.cross(arr1, arr2)
print(result)
print(arr1)
print(arr2)

[-3  6 -3]
[1 2 3]
[4 5 6]
