In [1]:
import numpy as np 

In [2]:
array1 = np.array([1,2,3,4,5,6])

In [3]:
array2 = np.empty((2,3))
array2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
array1.ndim

1

In [5]:
array2.shape

(2, 3)

In [6]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,20]])

In [7]:
array3.shape

(2, 5)

In [8]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

How to reshape the array 

In [9]:
array3.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 20]])

In [10]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

In [11]:
array3.shape

(2, 5)

In [12]:
array3.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [20]])

# Indexing and slicing 

In [13]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [14]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
print(array3[1,2])

8


In [16]:
array4 = np.array((2,5),dtype=np.int64)
array4

array([2, 5])

In [17]:
row = array3[1,:]
row

array([ 6,  7,  8,  9, 10])

In [18]:
# Access 2nd colum
col = array3[:,1]
col

array([ 2,  7, 12,  2,  7, 12])

In [19]:
rows_slice = array3[0:2, :] # Selects the first two rows (indices 0 and 1)
print(rows_slice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
sub_array = array3[0:2, 0:2] # Selects the top-left 2x2 sub-array
print(sub_array)

[[1 2]
 [6 7]]


In [21]:
stepped_rows = array3[::2, :] # Selects every other row
print(stepped_rows)


[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [ 6  7  8  9 10]]


In [22]:
tes1 = np.arange(0,100,5)

In [23]:
tes1.reshape(2,10)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [25]:
np.linspace(0,100,10, dtype=np.int64)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [ ]:
x = np.linspace(0,10,num=10,dtype=np.int64)
x = x.reshape(5,2)
y = np.linspace(11,100,num=10,dtype=np.int64)
y = y.reshape(5,2)
t = np.concatenate(x,y,axis=0)

_IncompleteInputError: incomplete input (2992506467.py, line 5)