In [22]:
import numpy as np 

In [23]:
array1 = np.array([1,2,3,4,5,6])

In [24]:
array2 = np.empty((2,3))
array2

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [25]:
array1.ndim

1

In [26]:
array2.shape

(2, 3)

In [27]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,20]])

In [28]:
array3.shape

(2, 5)

In [29]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

How to reshape the array 

In [30]:
array3.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 20]])

In [31]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

In [32]:
array3.shape

(2, 5)

In [33]:
array3.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [20]])

# Indexing and slicing 

In [34]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [35]:
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
print(array3[1,2])

8


In [43]:
array4 = np.array((2,5),dtype=np.int64)
array4

array([2, 5])

In [37]:
row = array3[1,:]
row

array([ 6,  7,  8,  9, 10])

In [38]:
# Access 2nd colum
col = array3[:,1]
col

array([ 2,  7, 12,  2,  7, 12])

In [39]:
rows_slice = array3[0:2, :] # Selects the first two rows (indices 0 and 1)
print(rows_slice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
sub_array = array3[0:2, 0:2] # Selects the top-left 2x2 sub-array
print(sub_array)

[[1 2]
 [6 7]]


In [45]:
stepped_rows = array3[::2, :] # Selects every other row
print(stepped_rows)


[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [ 6  7  8  9 10]]


In [50]:
tes1 = np.arange(0,100,5)

In [53]:
tes1.reshape(2,10)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])